### ISSUE TITLE
WebDAV image upload

### ISSUE THREAD

**Issue by oblivian** [fraschetti/Octoslack#64] opened 2019-09-02 07:19 UTC
Hey,

Thanks for a super great plugin. Would you concider adding support for WebDAV posting/upload of images? Hence a general agnostic image upload function. Most if not all cloud services support WebDAV, and would make it easier to integrate, be it OneDrive, Dropbox, Nextcloud or any other self-hosted web server, etc.

Thanks.

**Comment by calonmerc** [comment] 2019-09-19 14:06
Duplicate of #37

**Comment by fraschetti** [comment] 2022-11-08 07:08
Closing as duplicate.

**Closed by fraschetti** 2022-11-08 07:08 UTC
Labels: duplicate, enhancement
