### ISSUE TITLE
[Feature Request] Limit commands to UserID

### ISSUE THREAD

**Issue by Mortikhan** [fraschetti/Octoslack#56] opened 2019-06-24 16:29 UTC
OctoSlack is awesome. Just wish I could limit the use of the commands by other users. 
I have a slack group set up for 3d-printing geeks, and being able to see what everyone has printed is awesome, but I'd like to be able to limit the use of commands to my printers to just my userid instead of everyone in slack being able to stop my prints. 

or being able to turn individual commands on or off would be a great addition, then I could only enable the commands I wanted others to use (i.e. status). So a listen toggle per command. 
I don't really need or want to stop or pause a print from slack, but being able to allow others to get a status of my prints would be awesome.

**Comment by fraschetti** [comment] 2019-06-28 06:52
Duplicate of https://github.com/fraschetti/Octoslack/issues/52

Check there for the update on this issue (surprise - the coding is already done).

**Closed by fraschetti** 2019-06-28 06:52 UTC
Labels: duplicate, enhancement
